/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaskSubmission {
    id: bigint;
    cancelled: boolean;
    userId: bigint;
    completed: boolean;
    submittedAt?: Time;
    taskId: bigint;
    submissionLink?: string;
    withdrawn: boolean;
}
export type Time = bigint;
export interface Reward {
    id: bigint;
    redeemedAt?: Time;
    userId: bigint;
    redeemed: boolean;
    createdAt: Time;
    type: RewardType;
    amount: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Task {
    id: bigint;
    title: string;
    retrainingRewardPercentage: bigint;
    buyersRewardPercentage: bigint;
    type: TaskType;
    bonus: bigint;
    workforceRewardPercentage: bigint;
    price: bigint;
}
export interface Author {
    id: bigint;
    verified: boolean;
    bannedAt?: Time;
    name: string;
    banned: boolean;
    verifiedAt?: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    referralCode?: string;
    name: string;
    mobile?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum RewardType {
    taskCompletion = "taskCompletion",
    referral = "referral",
    bonus = "bonus",
    loyalty = "loyalty"
}
export enum TaskType {
    imageAnnotation = "imageAnnotation",
    transcription = "transcription",
    survey = "survey",
    appDownload = "appDownload",
    complexResearch = "complexResearch",
    simpleResearch = "simpleResearch"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBonus(userId: bigint, amount: bigint): Promise<void>;
    addCommission(userId: bigint, amount: bigint): Promise<void>;
    approveTaskSubmission(submissionId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banAuthor(authorId: bigint): Promise<void>;
    cancelInvoice(invoiceId: bigint): Promise<void>;
    cancelTaskSubmission(submissionId: bigint): Promise<void>;
    claimBonus(userId: bigint): Promise<bigint>;
    claimCommission(userId: bigint): Promise<bigint>;
    createAuthor(name: string): Promise<void>;
    createReward(userId: bigint, amount: bigint, type: RewardType, redeemed: boolean): Promise<void>;
    createTask(title: string, price: bigint, taskType: TaskType, bonus: bigint, buyersRewardPercentage: bigint, workforceRewardPercentage: bigint, retrainingRewardPercentage: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    getAllTasks(): Promise<Array<Task>>;
    getAuthor(authorId: bigint): Promise<Author>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTask(taskId: bigint): Promise<Task>;
    getTaskSubmissions(taskId: bigint): Promise<Array<TaskSubmission>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRewards(userId: bigint): Promise<Array<Reward>>;
    getUserSubmissions(userId: bigint): Promise<Array<TaskSubmission>>;
    isCallerAdmin(): Promise<boolean>;
    payInvoice(invoiceId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitInvoiceReward(invoiceId: bigint, rewardId: bigint): Promise<void>;
    submitTask(taskId: bigint, submissionLink: string): Promise<void>;
    transferReferralBonus(referrerId: bigint, rewardId: bigint): Promise<void>;
    updateTask(taskId: bigint, title: string, price: bigint, taskType: TaskType, bonus: bigint, buyersRewardPercentage: bigint, workforceRewardPercentage: bigint, retrainingRewardPercentage: bigint): Promise<void>;
    verifyAuthor(authorId: bigint): Promise<void>;
}
import type { Author as _Author, Reward as _Reward, RewardType as _RewardType, Task as _Task, TaskSubmission as _TaskSubmission, TaskType as _TaskType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBonus(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBonus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBonus(arg0, arg1);
            return result;
        }
    }
    async addCommission(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommission(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommission(arg0, arg1);
            return result;
        }
    }
    async approveTaskSubmission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTaskSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTaskSubmission(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banAuthor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banAuthor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banAuthor(arg0);
            return result;
        }
    }
    async cancelInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelInvoice(arg0);
            return result;
        }
    }
    async cancelTaskSubmission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTaskSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTaskSubmission(arg0);
            return result;
        }
    }
    async claimBonus(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.claimBonus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimBonus(arg0);
            return result;
        }
    }
    async claimCommission(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.claimCommission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimCommission(arg0);
            return result;
        }
    }
    async createAuthor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAuthor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAuthor(arg0);
            return result;
        }
    }
    async createReward(arg0: bigint, arg1: bigint, arg2: RewardType, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReward(arg0, arg1, to_candid_RewardType_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReward(arg0, arg1, to_candid_RewardType_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createTask(arg0: string, arg1: bigint, arg2: TaskType, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, to_candid_TaskType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, to_candid_TaskType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthor(arg0: bigint): Promise<Author> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthor(arg0);
                return from_candid_Author_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthor(arg0);
            return from_candid_Author_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: bigint): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskSubmissions(arg0: bigint): Promise<Array<TaskSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskSubmissions(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskSubmissions(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRewards(arg0: bigint): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRewards(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRewards(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubmissions(arg0: bigint): Promise<Array<TaskSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubmissions(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubmissions(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async payInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.payInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payInvoice(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitInvoiceReward(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInvoiceReward(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInvoiceReward(arg0, arg1);
            return result;
        }
    }
    async submitTask(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTask(arg0, arg1);
            return result;
        }
    }
    async transferReferralBonus(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferReferralBonus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferReferralBonus(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: bigint, arg3: TaskType, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_TaskType_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_TaskType_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async verifyAuthor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAuthor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAuthor(arg0);
            return result;
        }
    }
}
function from_candid_Author_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Author): Author {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RewardType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardType): RewardType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Reward_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reward): Reward {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TaskSubmission_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskSubmission): TaskSubmission {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    retrainingRewardPercentage: bigint;
    buyersRewardPercentage: bigint;
    type: _TaskType;
    bonus: bigint;
    workforceRewardPercentage: bigint;
    price: bigint;
}): {
    id: bigint;
    title: string;
    retrainingRewardPercentage: bigint;
    buyersRewardPercentage: bigint;
    type: TaskType;
    bonus: bigint;
    workforceRewardPercentage: bigint;
    price: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        retrainingRewardPercentage: value.retrainingRewardPercentage,
        buyersRewardPercentage: value.buyersRewardPercentage,
        type: from_candid_TaskType_n17(_uploadFile, _downloadFile, value.type),
        bonus: value.bonus,
        workforceRewardPercentage: value.workforceRewardPercentage,
        price: value.price
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    verified: boolean;
    bannedAt: [] | [_Time];
    name: string;
    banned: boolean;
    verifiedAt: [] | [_Time];
}): {
    id: bigint;
    verified: boolean;
    bannedAt?: Time;
    name: string;
    banned: boolean;
    verifiedAt?: Time;
} {
    return {
        id: value.id,
        verified: value.verified,
        bannedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.bannedAt)),
        name: value.name,
        banned: value.banned,
        verifiedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.verifiedAt))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: [] | [string];
    name: string;
    mobile: [] | [string];
}): {
    referralCode?: string;
    name: string;
    mobile?: string;
} {
    return {
        referralCode: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.referralCode)),
        name: value.name,
        mobile: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.mobile))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cancelled: boolean;
    userId: bigint;
    completed: boolean;
    submittedAt: [] | [_Time];
    taskId: bigint;
    submissionLink: [] | [string];
    withdrawn: boolean;
}): {
    id: bigint;
    cancelled: boolean;
    userId: bigint;
    completed: boolean;
    submittedAt?: Time;
    taskId: bigint;
    submissionLink?: string;
    withdrawn: boolean;
} {
    return {
        id: value.id,
        cancelled: value.cancelled,
        userId: value.userId,
        completed: value.completed,
        submittedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.submittedAt)),
        taskId: value.taskId,
        submissionLink: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.submissionLink)),
        withdrawn: value.withdrawn
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    redeemedAt: [] | [_Time];
    userId: bigint;
    redeemed: boolean;
    createdAt: _Time;
    type: _RewardType;
    amount: bigint;
}): {
    id: bigint;
    redeemedAt?: Time;
    userId: bigint;
    redeemed: boolean;
    createdAt: Time;
    type: RewardType;
    amount: bigint;
} {
    return {
        id: value.id,
        redeemedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.redeemedAt)),
        userId: value.userId,
        redeemed: value.redeemed,
        createdAt: value.createdAt,
        type: from_candid_RewardType_n34(_uploadFile, _downloadFile, value.type),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageAnnotation: null;
} | {
    transcription: null;
} | {
    survey: null;
} | {
    appDownload: null;
} | {
    complexResearch: null;
} | {
    simpleResearch: null;
}): TaskType {
    return "imageAnnotation" in value ? TaskType.imageAnnotation : "transcription" in value ? TaskType.transcription : "survey" in value ? TaskType.survey : "appDownload" in value ? TaskType.appDownload : "complexResearch" in value ? TaskType.complexResearch : "simpleResearch" in value ? TaskType.simpleResearch : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskCompletion: null;
} | {
    referral: null;
} | {
    bonus: null;
} | {
    loyalty: null;
}): RewardType {
    return "taskCompletion" in value ? RewardType.taskCompletion : "referral" in value ? RewardType.referral : "bonus" in value ? RewardType.bonus : "loyalty" in value ? RewardType.loyalty : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskSubmission>): Array<TaskSubmission> {
    return value.map((x)=>from_candid_TaskSubmission_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reward>): Array<Reward> {
    return value.map((x)=>from_candid_Reward_n32(_uploadFile, _downloadFile, x));
}
function to_candid_RewardType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewardType): _RewardType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode?: string;
    name: string;
    mobile?: string;
}): {
    referralCode: [] | [string];
    name: string;
    mobile: [] | [string];
} {
    return {
        referralCode: value.referralCode ? candid_some(value.referralCode) : candid_none(),
        name: value.name,
        mobile: value.mobile ? candid_some(value.mobile) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewardType): {
    taskCompletion: null;
} | {
    referral: null;
} | {
    bonus: null;
} | {
    loyalty: null;
} {
    return value == RewardType.taskCompletion ? {
        taskCompletion: null
    } : value == RewardType.referral ? {
        referral: null
    } : value == RewardType.bonus ? {
        bonus: null
    } : value == RewardType.loyalty ? {
        loyalty: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    imageAnnotation: null;
} | {
    transcription: null;
} | {
    survey: null;
} | {
    appDownload: null;
} | {
    complexResearch: null;
} | {
    simpleResearch: null;
} {
    return value == TaskType.imageAnnotation ? {
        imageAnnotation: null
    } : value == TaskType.transcription ? {
        transcription: null
    } : value == TaskType.survey ? {
        survey: null
    } : value == TaskType.appDownload ? {
        appDownload: null
    } : value == TaskType.complexResearch ? {
        complexResearch: null
    } : value == TaskType.simpleResearch ? {
        simpleResearch: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
