/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Author {
  'id' : bigint,
  'verified' : boolean,
  'bannedAt' : [] | [Time],
  'name' : string,
  'banned' : boolean,
  'verifiedAt' : [] | [Time],
}
export interface Reward {
  'id' : bigint,
  'redeemedAt' : [] | [Time],
  'userId' : bigint,
  'redeemed' : boolean,
  'createdAt' : Time,
  'type' : RewardType,
  'amount' : bigint,
}
export type RewardType = { 'taskCompletion' : null } |
  { 'referral' : null } |
  { 'bonus' : null } |
  { 'loyalty' : null };
export interface Task {
  'id' : bigint,
  'title' : string,
  'retrainingRewardPercentage' : bigint,
  'buyersRewardPercentage' : bigint,
  'type' : TaskType,
  'bonus' : bigint,
  'workforceRewardPercentage' : bigint,
  'price' : bigint,
}
export interface TaskSubmission {
  'id' : bigint,
  'cancelled' : boolean,
  'userId' : bigint,
  'completed' : boolean,
  'submittedAt' : [] | [Time],
  'taskId' : bigint,
  'submissionLink' : [] | [string],
  'withdrawn' : boolean,
}
export type TaskType = { 'imageAnnotation' : null } |
  { 'transcription' : null } |
  { 'survey' : null } |
  { 'appDownload' : null } |
  { 'complexResearch' : null } |
  { 'simpleResearch' : null };
export type Time = bigint;
export interface UserProfile {
  'referralCode' : [] | [string],
  'name' : string,
  'mobile' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBonus' : ActorMethod<[bigint, bigint], undefined>,
  'addCommission' : ActorMethod<[bigint, bigint], undefined>,
  'approveTaskSubmission' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banAuthor' : ActorMethod<[bigint], undefined>,
  'cancelInvoice' : ActorMethod<[bigint], undefined>,
  'cancelTaskSubmission' : ActorMethod<[bigint], undefined>,
  'claimBonus' : ActorMethod<[bigint], bigint>,
  'claimCommission' : ActorMethod<[bigint], bigint>,
  'createAuthor' : ActorMethod<[string], undefined>,
  'createReward' : ActorMethod<
    [bigint, bigint, RewardType, boolean],
    undefined
  >,
  'createTask' : ActorMethod<
    [string, bigint, TaskType, bigint, bigint, bigint, bigint],
    undefined
  >,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAuthor' : ActorMethod<[bigint], Author>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTaskSubmissions' : ActorMethod<[bigint], Array<TaskSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRewards' : ActorMethod<[bigint], Array<Reward>>,
  'getUserSubmissions' : ActorMethod<[bigint], Array<TaskSubmission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'payInvoice' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInvoiceReward' : ActorMethod<[bigint, bigint], undefined>,
  'submitTask' : ActorMethod<[bigint, string], undefined>,
  'transferReferralBonus' : ActorMethod<[bigint, bigint], undefined>,
  'updateTask' : ActorMethod<
    [bigint, string, bigint, TaskType, bigint, bigint, bigint, bigint],
    undefined
  >,
  'verifyAuthor' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];