/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RewardType = IDL.Variant({
  'taskCompletion' : IDL.Null,
  'referral' : IDL.Null,
  'bonus' : IDL.Null,
  'loyalty' : IDL.Null,
});
export const TaskType = IDL.Variant({
  'imageAnnotation' : IDL.Null,
  'transcription' : IDL.Null,
  'survey' : IDL.Null,
  'appDownload' : IDL.Null,
  'complexResearch' : IDL.Null,
  'simpleResearch' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'retrainingRewardPercentage' : IDL.Nat,
  'buyersRewardPercentage' : IDL.Nat,
  'type' : TaskType,
  'bonus' : IDL.Nat,
  'workforceRewardPercentage' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const Author = IDL.Record({
  'id' : IDL.Nat,
  'verified' : IDL.Bool,
  'bannedAt' : IDL.Opt(Time),
  'name' : IDL.Text,
  'banned' : IDL.Bool,
  'verifiedAt' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'mobile' : IDL.Opt(IDL.Text),
});
export const TaskSubmission = IDL.Record({
  'id' : IDL.Nat,
  'cancelled' : IDL.Bool,
  'userId' : IDL.Nat,
  'completed' : IDL.Bool,
  'submittedAt' : IDL.Opt(Time),
  'taskId' : IDL.Nat,
  'submissionLink' : IDL.Opt(IDL.Text),
  'withdrawn' : IDL.Bool,
});
export const Reward = IDL.Record({
  'id' : IDL.Nat,
  'redeemedAt' : IDL.Opt(Time),
  'userId' : IDL.Nat,
  'redeemed' : IDL.Bool,
  'createdAt' : Time,
  'type' : RewardType,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBonus' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addCommission' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'approveTaskSubmission' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banAuthor' : IDL.Func([IDL.Nat], [], []),
  'cancelInvoice' : IDL.Func([IDL.Nat], [], []),
  'cancelTaskSubmission' : IDL.Func([IDL.Nat], [], []),
  'claimBonus' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'claimCommission' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'createAuthor' : IDL.Func([IDL.Text], [], []),
  'createReward' : IDL.Func([IDL.Nat, IDL.Nat, RewardType, IDL.Bool], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Nat, TaskType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAuthor' : IDL.Func([IDL.Nat], [Author], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTaskSubmissions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TaskSubmission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRewards' : IDL.Func([IDL.Nat], [IDL.Vec(Reward)], ['query']),
  'getUserSubmissions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TaskSubmission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'payInvoice' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInvoiceReward' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'submitTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'transferReferralBonus' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        TaskType,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'verifyAuthor' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RewardType = IDL.Variant({
    'taskCompletion' : IDL.Null,
    'referral' : IDL.Null,
    'bonus' : IDL.Null,
    'loyalty' : IDL.Null,
  });
  const TaskType = IDL.Variant({
    'imageAnnotation' : IDL.Null,
    'transcription' : IDL.Null,
    'survey' : IDL.Null,
    'appDownload' : IDL.Null,
    'complexResearch' : IDL.Null,
    'simpleResearch' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'retrainingRewardPercentage' : IDL.Nat,
    'buyersRewardPercentage' : IDL.Nat,
    'type' : TaskType,
    'bonus' : IDL.Nat,
    'workforceRewardPercentage' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Author = IDL.Record({
    'id' : IDL.Nat,
    'verified' : IDL.Bool,
    'bannedAt' : IDL.Opt(Time),
    'name' : IDL.Text,
    'banned' : IDL.Bool,
    'verifiedAt' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'mobile' : IDL.Opt(IDL.Text),
  });
  const TaskSubmission = IDL.Record({
    'id' : IDL.Nat,
    'cancelled' : IDL.Bool,
    'userId' : IDL.Nat,
    'completed' : IDL.Bool,
    'submittedAt' : IDL.Opt(Time),
    'taskId' : IDL.Nat,
    'submissionLink' : IDL.Opt(IDL.Text),
    'withdrawn' : IDL.Bool,
  });
  const Reward = IDL.Record({
    'id' : IDL.Nat,
    'redeemedAt' : IDL.Opt(Time),
    'userId' : IDL.Nat,
    'redeemed' : IDL.Bool,
    'createdAt' : Time,
    'type' : RewardType,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBonus' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addCommission' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'approveTaskSubmission' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banAuthor' : IDL.Func([IDL.Nat], [], []),
    'cancelInvoice' : IDL.Func([IDL.Nat], [], []),
    'cancelTaskSubmission' : IDL.Func([IDL.Nat], [], []),
    'claimBonus' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'claimCommission' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'createAuthor' : IDL.Func([IDL.Text], [], []),
    'createReward' : IDL.Func([IDL.Nat, IDL.Nat, RewardType, IDL.Bool], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Nat, TaskType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAuthor' : IDL.Func([IDL.Nat], [Author], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTaskSubmissions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TaskSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRewards' : IDL.Func([IDL.Nat], [IDL.Vec(Reward)], ['query']),
    'getUserSubmissions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TaskSubmission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'payInvoice' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInvoiceReward' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'submitTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'transferReferralBonus' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          TaskType,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'verifyAuthor' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };